- name: remove pip cache
  command: rm -rf ~/.cache/pip

- name: remove apt cache
  command: apt-get clean

- name: remove apt cache directory
  command: rm -rf /var/lib/apt/lists/*

- name: remove temporary files
  command: rm -rf /tmp/* /var/tmp/*
